### ISSUE TITLE
chore: Migrate to clap 3.0 from structopt

### ISSUE THREAD

**Issue by ThePuzzlemaker** [calypso-lang/calypso#111]
Clap 3.0 was recently released, including built-in support for structopt, which we already use.

This is a bit of a chore--I'll get to it at some point--but if anyone would like to help that would be appreciated.

A migration guide is available [here](https://github.com/clap-rs/clap/blob/v3.0.1/CHANGELOG.md#migrating)--specifically, see the subsection "From structopt 0.3.25".

**Comment by tbmreza** [comment]
Please have a look 🤓 #118

**Comment by ThePuzzlemaker** [comment]
Thanks very much!
@all-contributors add @tbmreza for tests, maintenance

**Comment by tbmreza** [comment]
you're welcome! 😊 @ThePuzzlemaker
